---
title: "CONTRIBUTIONS"
author: "Monica Penner"
date: "2/16/2022"
output: html_document
---

### Summary of Contributions

## Contribution Inventory and Timeline

- Please refer to the [Rancor Gannt Chart](https://github.com/The0therChad/star.rank/blob/main/RancorGanntFeb15Edit.xlsx) for the detailed contribution inventory and timeline 

### Roger's Strengths

- Code creation driver
- API selection driver
- Equal creative contributor 

### Chad's Strengths

- Software expertice
- Git branch management
- Primary code contributor
- Equal creative contributor

### Monica's Strengths

- Supporting documentation driver 
- Process flow mapper
- Equal creative contributor

## Things that went well

- Excellent adherence to the Star.rank Code of Conduct
- Multiple opportunities to work together in person, expedited work flow

## Challenges Encountered -> adjustments made

- Delay in confirming API -> timeline re-adjusted and condensed (All)
- Star Wars API wrapper already developed -> elevate and focus functionality of wrapper (All)
- Jupyter lab /GitHub conflict -> switch to Rstudio (Chad)
- Expired Travis CI free trial -> switch to GitHub integration system (Chad)
- Incorrect branch creation technique -> consolidate branches (Chad)
- Pipe %>% conflict (Monica) -> add pipe utility (Chad)
- Rapid code creation and problem solving at end of project -> in person work sessions (Feb 17, 18, 19) to allow for direct/instantaneous communication (All)
- SWAPI website became unaccessible February 19th -> attach note to failing CI badge
