---
title: "ProjectNotebookData534"
author: "Monica Penner"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Table of Contents

### A) Timeline of Monica Specific Work
#### Jan 20 (backfilled)
#### Jan 20-Feb 15 (backfilled)
#### Feb 14 (backfilled)
#### Feb 15
#### Feb 16
#### Feb 17 (backfilled)
#### Feb 19

### B) Communication Events

### C) Major Decision Points

***********************************************************************

## A) Timeline of Monica Specific Work (C when complete)
### 1) February 15, 2022
- notebook creation (C)
- backfill previous work info (C)
- project confirmation emails (C)
- Code of Conduct documentation 
- Contributions documentation 

### 2) January 20, 2022
- (backfilled info)
- review project criteria
- discuss possible API choices
- discuss individual strengths and weaknesses
- start work allocation

### 3) January 20 to February 14, 2022
- review possible APIs (C)
- review various API wrappers (C)

### 4) February 14, 2022
- review Travis CI processes (C)
- review StarWars API (C)

### 5) February 15, 2022 
- create personal project log https://github.com/The0therChad/star.rank/commit/ee91f8753ba0deebf979ffc8a04214c1ed2ce259
- create Code of Conduct https://github.com/The0therChad/star.rank/commit/ca80830d8cb209f19a350f5faeea1aa1d6d95c31
- create CONTRIBUTIONS https://github.com/The0therChad/star.rank/commit/ca80830d8cb209f19a350f5faeea1aa1d6d95c31
- create gannt contribution/timeline https://github.com/The0therChad/star.rank/blob/main/RancorGanntFeb15Edit.xlsx

### 5) February 16, 2022 
- outline function options
- first attempt species function https://github.com/The0therChad/star.rank/commit/20fce8f43e1c296855dff43a68ef82a98a02f2c1

### 6) February 17, 2022
- except/test code background work
- modify species code https://github.com/The0therChad/star.rank/commit/c0d52620f276e02d226febf4d292d568aabbd364

### 7) February 18, 2022 (backfill)
- error work
- attempt test code

### 8) February 19, 2022
- review and pull Chad's work https://github.com/The0therChad/star.rank/commit/8b9389b7566397ed1af50f6f41c5ba8b1b043a8b
- update species documentation https://github.com/The0therChad/star.rank/commit/5de0542f8524523365d54a924eeed85da09707cd
- n feature and film counts to all functions https://github.com/The0therChad/star.rank/commit/481f1a022afc42da370c855a3e65961ff7267c17
- create films function https://github.com/The0therChad/star.rank/commit/406570c3b4fdc55eb1f7b7c1c4c2f8d35d461f9f
- README edits https://github.com/The0therChad/star.rank/commit/bfbf8c3cc3ee9277e64fce39e65045ac04fc9aac
- log updates https://github.com/The0therChad/star.rank/commit/7d09c92d8c18c3efddf704f6d88df8809245b8d8
- Final documentation edits https://github.com/The0therChad/star.rank/commit/46290c978a7a6ead57589cd2973001674c4aad32

## B) Communication Events
-Date - medium: (primary person) topic

- Jan 20 - slack: group set up, introductions
- Jan 20 - dinner: API options, individual strengths
- Feb 13 - slack: (Roger) Star Wars API proposal
- Feb 14 - classroom: nightly task assignment: Roger function building, Chad folder set up, Monica Travis CI enquiry
- Feb 14 - slack: (Roger) python function presentation
- Feb 15 - classroom: (Chad) repo launch
- Feb 15 - email: (Monica) API approval request to Dr Lucet
- Feb 15 - zoom: discussion and decision to proceed with Star Wars API, decision to focus wrapper on Ranking (AKA Rancor), nightly task assignment: Roger function modification, Chad proj framework/folder completion, Monica Code of Conduct, Contributions documentation
- Feb 16 - classroom: function code creation
- Feb 17 - classroom: function code creation, task division
- Feb 17 - slack: code creation hiccups (evening)
- Feb 18 - slack: multiple times re: dplyr pipe error
- Feb 19 - slack : multiple times to coordinate next steps as each task completed
- Feb 19 - classroom: (Chad, Monica, Roger excused)
 


## C) Major Decision Points
- Jan 20: Partner Selection
- Feb 14: Star Wars API
- Feb 15: Continue with Star Wars API
- Feb 17: Use plot code developed by Roger
- Feb 18: Use improved function code developed by Chad
- Feb 19: Agree to proceed with films function development


