---
title: "StarRankCodeOfConduct"
author: "TheOtherChad, obsprof, Energix11"
date: "2/15/2022"
output:
  pdf_document: default
  html_document: default
---


## Star.rank Code of Conduct

The star.rank code of conduct is a reflection of our common goals, principles and ethical values.  

#### _Participants will epitomize the following values in every aspect of our obligations and interactions:_  

1. **Respect** - Mutual trust and respect are the cornerstones to productive interactions.  Security from judgement, safety from rivalry and quietude support freedom of expression and creative thought.  

2. **Dedication** - Individuals who are accountable and work to the best of their ability promote project advancement and shared goal achievement.  

3. **Inclusivity** - Acknowledgement and appreciation of differing life experiences and individual strengths promotes diversity, participation and expertise while maximizing productivity and proficiency. Acceptance and admission of one's own areas for improvement promotes personal growth and skills development.  

4. **Integrity** - Acting ethically and with authenticity produces outcomes that everyone can be proud of.  



#### _Participants will abide by the following key principles:_  

1. **Communication** - All interpersonal communication will be timely, courteous, concise, honest and genuine.  

2. **Collaboration** - Group members will participate enthusiastically and professionally.  

3. **Conflict Resolution** - Should conflict occur, avenues for remediation will be sought first through direct polite discourse, second through third party remediation and finally through formal institutional mechanisms.  Recognizing that all conflicts have at least two opposing views, confidentiality will be maintained within the project members.  


#### _Participants will maintain personal work standards that are:_  
 
1. **Project Focused** -  In recognition that the final product will be reflected back to each participant, group members will endeavour to prioritize project completion to the highest standard.  

2. **Self Aware** - Accepting that humans are fallible and very rarely perfect, project members will communicate potential challenges without judgement.  

3. **Joy Oriented** - Although successful project completion is the common goal, attention will be paid to enjoying the learning and comradery along the way.
