---
title: "blurb"
author: "Monica Penner"
date: "2/16/2022"
output: html_document
---
## What RancorGraphs does
- access [StarWars API]("https://swapi.dev/") information
- rank data:
  - related to people, planets, starships, vehicles, species and films 
  - based on a variety of metrics such as height, weight, cost, speed, lifespan and counts
  - filtered ascending or descending
  - user defined group sizes
- graphically display entire group distribution
- display rank results as a list? and graphically

### People/Characters
- height (centimeters)
- mass/weight (kilograms)
- popularity (film count)

### Planets 
- diameter (kilometers)
- rotation period (standard hours)
- orbital period (standard days)
- population (count)
- popularity (film count) 

### Starships
- cost (galactic credits)
- length (meters)
- crew (count of needed personnel to operate Starship)
- passengers (count)
- speed (max speed in the atmosphere)
- cargo capacity (kilograms)
- popularity (film count)

### Vehicles
- cost (galactic credits)
- length (meters)
- crew (count of needed personnel to operate Starship)
- passengers (count)
- speed (max speed in the atmosphere)
- cargo capacity (kilograms)
- popularity (film count)

### Species
- average height (centimeters)
- average lifespan (standard years)
- popularity (film count)

### Films
- oldest/newest (release date)
- character diversity (people count)
- technological diversity (starship and vehicle count)
- geographic diversity (planet count)
- species diversity(species count)
